server:
  port: 8080
spring:
  application:
    name: adal-web
  datasource:
    #    url: jdbc:mysql://127.0.0.1/adal
    #    username: root
    #    password: 123456
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://129.28.153.9/adal?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://129.28.153.9/adalslave1?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_2:
          url: jdbc:mysql://129.28.153.9/adalslave2?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 2
    host: 129.28.153.9
  rabbitmq:
    host: 129.28.153.9
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
mybatis-plus:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  type-aliases-package: me.baocai.adal.web.entity
  typeEnumsPackage: me.baocai.adal.web.enums
  mapper-locations:
    - mappers/*.xml
  global-config:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    db-config:
      logic-delete-field: deleted  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
  level:
    me.baocai: debug
    me.baocai.adal.web.repository: trace
springfox:
  documentation:
    swagger-ui:
      enabled: true
custom:
  config:
    ignores:
      # 需要过滤的 post 请求
      post:
        - "/api/auth/login"
        - "/api/auth/logout"
      get:
        - "/api/auth/**"
      # 需要过滤的请求，不限方法
      pattern:
        - "/test/*"
        - "/goods/*"
        - "/swagger-ui/**"
        - "/swagger-resources/**"
        - "/v3/**"