server:
  port: 8080
spring:
  application:
    name: adal-web
  datasource:
    url: jdbc:mysql://127.0.0.1/adal
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 2
    host: 127.0.0.1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  type-aliases-package: me.baocai.adal.web.model
  mapper-locations:
    - mappers/*.xml
logging:
  level:
    me.baocai: debug
    me.baocai.adal.web.repository: trace
custom:
  config:
    ignores:
      # 需要过滤的 post 请求
      post:
        - "/api/auth/login"
        - "/api/auth/logout"
      # 需要过滤的请求，不限方法
      pattern:
        - "/test/*"